### ISSUE TITLE
What value of parameter "a" is used for SCAD and MCP?

### ISSUE THREAD

**Issue by ytstat** [XiaoouPan/ILAMM#1]
Hi Xiaoou,

I couldn't find where to set this fixed parameter in function "cvNcvxHuberReg". So what's the default value of it? I guess 3.7 for SCAD, and what about MCP?

If possible, could you please add this parameter into the input arguments of "cvNcvxHuberReg" and other functions next time you update this package? Thanks!

**Comment by XiaoouPan** [comment]
Thank you so much for your comment and suggestion! We use 3.7 for SCAD and 3 for MCP.

I'll add this argument into the function.

**Comment by ytstat** [comment]
Thank you! I closed this post:)
